### ISSUE TITLE
Restoring closed window doesn't remember pinned tabs

### ISSUE THREAD

**Issue by MaaRak** [cxw42/TabFern#106]
When closing a window where some/all tabs are pinned, reopening the window reopens them all as unpinned tabs.

**Comment by cxw42** [comment]
MaaRak, thanks for using TabFern and for the report!  Would you please add a bit more detail?  This will help me figure out what is going on.  

 - I think you are referring to pinning in Chrome, by right-clicking on the tab and selecting "Pin tab."  Is that correct?

 - Are you closing the TabFern window itself, or the window that includes the pinned tabs (the one with ![monitor_add](https://user-images.githubusercontent.com/10515894/35530944-948263a2-0503-11e8-8914-27c1ae2e9916.png) by its name in the TabFern window)? 

 - How are you reopening the window?  By clicking on the ![folder-from-jstree-default-dark-32px](https://user-images.githubusercontent.com/10515894/35531006-c1b68cc2-0503-11e8-889b-58d3ce493689.png) folder icon in the TabFern window, or some other way?

 - Are you using the latest version of TabFern (v0.1.14)?

I have never used "Pin tab" myself, which is why it might not be supported by TabFern yet :) .  Thank you!

**Comment by cxw42** [comment]
@MaaRak I updated the code based on what I think you are referring to.  Does this look like the behaviour you want?  If I close the window and re-open it, the pinned tabs are still pinned.

![untitled](https://user-images.githubusercontent.com/10515894/35572105-e4721698-05a1-11e8-9507-fcade986a55b.png)

**Comment by MaaRak** [comment]
Hi cxw42!

To answer your original questions:

- Yes, this is referring to right-clicking and choosing 'pin tab,'
- Referring to closing the window with the pinned tabs,
- Re-opening by clicking either the folder icon or the window title right next to it, and:
- Yes, on the latest version, 0.1.14

And, yes, the pic you have in the second post does look like the behavior I'm looking for! Thanks for the quick response!

**Comment by cxw42** [comment]
@MaaRak You're welcome, and thanks for the additional detail!  If you know how to run Chrome extensions unpacked, check out branch v01f and you can try it now :) .  Otherwise, this fix will be included in the next release.  I am going to close this issue; feel free to add a comment or open a new issue if you have further questions/comments/suggestions/bug reports/&c.!

**Comment by cxw42** [comment]
Oh - and for purely selfish reasons, I'll ask --- would you mind starring the project if it is helpful to you?  I'll take all the free publicity I can get :D .

**Comment by MaaRak** [comment]
Tested and works like a charm! Happily starred, thanks again! This is already a huge improvement to the dead Tab Outliner extension.

**Comment by cxw42** [comment]
Drag-and-drop of a pinned node from a closed window to an open window loses the "pinned tab" setting.

**Comment by cxw42** [comment]
Bug fixed --- MaaRak, grab the latest if you're continuing to run unpacked.
