### ISSUE TITLE
Vivaldi browser compatibility

### ISSUE THREAD

**Issue by aleinthesky** [cxw42/TabFern#123]
Hi! I love this fantastic extension, and I'd like to use it on the Vivaldi browser, which provides users with a great utility of configurable side panel for pages and extensions. Unfortunately, on the Vivaldi browser, TabFern does not work perfectly. At startup a message appears saying "Initialization not complete, changes will not be saved" and, indeed, the sessions are not saved and can not be renamed. I hope you can make your extension compatible with Vivaldi. Thank you very much for your attention.

**Comment by cxw42** [comment]
@aleinthesky Thanks for the positive feedback!  I am happy to work on Vivaldi as I have opportunity.  However, I cannot give you any specific timeframe.  I am also hoping to port to Firefox at some point (#100).

Are you able to use TabFern on Vivaldi for any tasks?  Does it show the open windows/tabs, and update as you open/close/rearrange tabs?  What level of functionality does it have?

The next version will have better error reporting on startup, which may help me debug further.

**Comment by cxw42** [comment]
@aleinthesky By the way, based on your comments above, would you mind dropping a star on the project?  :D

**Comment by cxw42** [comment]
I took a quick look using a [standalone install](https://help.vivaldi.com/article/standalone-version-of-vivaldi/) of Vivaldi 1.15.1147.36 (Stable channel) (32-bit) on Win8.1 x64.  TabFern initialized successfully in my testing, both with the current Web Store version (v0.1.16) and my current working version (v0.2.0-pre.1).  I did fix one bug that prevented the Settings page from being opened.

@aleinthesky which version of Vivaldi are you running, which OS, and which configuration (all users/single user/standalone)?  Are you comfortable loading unpacked extensions, and if so, would you be willing to try the latest?

**Comment by cxw42** [comment]
@aleinthesky I hope you already saw this, but recently-released v0.1.17 runs in Vivaldi! :tada:  Feel free to open a new issue if you encounter any problems.

**Comment by philiprhoades** [comment]
@cxw42 ,

I just tried Version 0.1.19 on Fedora 28 x86_64 Vivialdi 2.0.1309.42 (Stable channel) (64-bit) but clicking the button displayed a blank screen at first and then later attempts worked - not sure what was going on.

Anyway, TabFern looks like it could be a full replacement for TO (the unresponsive developer has been driving me crazy for years!) with a bit more work - happy to help however I can!

Thanks!
Phil.

**Comment by cxw42** [comment]
@philiprhoades Phil, Thanks for the feedback and kind words!  Please let me know if you experience further problems.  You can also try double-clicking the TF icon, which will summon the TF window to the current browser window if the TF window is offscreen (#141).

If you have any coding time, or speak any languages other than English, I would certainly appreciate any contributions you care to make!  Some of the issues are tagged "help wanted" or "good first issue," but anything not already assigned to someone is up for grabs.

I could also use beta testers - would you be willing to use a prerelease version and give me any feedback you have?  If so, let me know whether you are comfortable loading extensions unpacked, or whether you would like to load a prerelease from the Chrome Web store (#122).  The big news in the next version will be #35 - check it out :) .

Finally, as you may have noticed, the documentation lags behind the software.  I would be delighted to receive documentation contributions as well.

Whether or not you have time to contribute, I would certainly appreciate your support of the project by starring it here and telling others about it!  The more users we have, the more robust we can make TF.

Thank you!
Chris

**Comment by philiprhoades** [comment]
@cxw42 
Chris,

Thanks for the informative reply!
My coding / OS background is:

- *nix->DOS->Windows->Xenix 386->Linux (from 0.9 kernels)
- Fortran IV (a long time ago now)->Basic->C->C++(a little)->Ruby

and I could probably help with most of those other things you mentioned.  Since TO has become central to the way I operate in terms of dealing with lots of projects and masses of windows and tabs, and since the developer is so unresponsive, I am very happy to help develop an open alternative!

Regards,
Phil.

**Comment by cxw42** [comment]
Phil, sounds good!  You know your skills in detail, and I don't --- what would be the easiest or most feasible thing on my list above for you to start with?  Let me know, and I'll be able to do any preparatory work that may be necessary on my end.

**Comment by philiprhoades** [comment]
@cxw42 Chris, the first thing I would like to do is test the #35 alpha code operation - but I can't see that that is available yet?  I guess there needs to be a separate Git fork created?  

I am happy to start exploring JS but opening single tabs is a big deal for me. I have manually installed a few extensions.

BTW, I find I can have both TO and TF going at the same time which is quite convenient because I can get familiar with TF while I can revert to the TO tree when I need to get something that I haven't shifted over to TF yet. It is working out nicely! I am quite enjoying the switch from Chrome to Vivaldi and the associated switch from TO to TF! (even though it looks like it was not a Chrome problem after all that started the conversion process . . oh well it is all for the better I think anyway).

Thanks!

**Comment by cxw42** [comment]
Phil, I am attaching the built source of the latest, which calls itself "TFSwitch".  Unzip and load it as an unpacked extension and you should be ready to try it out!  Please report any bugs at the appropriate issues (e.g., Vivaldi-specific things here, or single-tab things at #35).  See #4 for information if you want to build it yourself from git - the current branch is `switchover` (whence the name).

Please note this will load as a separate extension from TabFern.  Therefore, back up your tabs and settings in TabFern, and then load them in TFSwitch.

[webstore-0.2.0-pre.4.zip](https://github.com/cxw42/TabFern/files/2495463/webstore-0.2.0-pre.4.zip)

**Comment by philiprhoades** [comment]
Will have a quick look before I need catch up on some sleep that I have been missing because of these Chrome / system crashes! (I am on Sydney time).

**Comment by philiprhoades** [comment]
Looks good! I am writing this from a single tab that was opened from my "Vivaldi / TabFern" saved window. I still get the single empty, white window if I single click on the orange icon but double-clicking works as you said.  I will keep using this version and provide feedback etc as I start finding my way around the code - I saw there was one error that showed up. Actually I should say, if Vivaldi wasn't able to use Chrome Extensions, I would never have ended up here . . at least not as quickly . . and I am hoping the Developer environment to be equally as friendly as Chrome . .

**Comment by cxw42** [comment]
@philiprhoades Glad to hear it loaded OK!  My experience is that Vivaldi generally is fairly developer-friendly.

I did want to mention that TF and Vivaldi overlap in philosophy to the extent that they both provide lots of options!  If you haven't checked out Settings | Behaviour, please make sure you do so.

Sleep well!

**Comment by philiprhoades** [comment]
@cxw42 Chris, Everything is going quite well! Yes, I haven't quite made it to bed yet and I was looking at the options - I changed the background to Light instead of Dark. I have now opened (from TO) my five routinely used windows (but usually only with a few of the 20-50 tabs each) and my new V/TF window with all the tabs.

The first thing I notice is that both open and closed tabs are the same colour? On TO, the closed tabs are white text instead of black.  TO has a grey "Light" background so you can still see the text for the closed tabs - although it is not easy to read until you select it - which is another difference - single clicking in TF actually opens the tab / window instead of selecting it - a few things to get used to but it is much better than I was expecting really.

**Comment by cxw42** [comment]
- Same-color tabs: opened new #155 (currently, the only visual distinction in the Light theme is when you hover the mouse over a tab's entry in the tree: closed tabs have a yellow background and open tabs have a blue background).
- Single- vs. double-click: open as #64 

Thanks!

**Comment by XellossMetallium** [comment]
Hi, I'm a new user of both TabFern and Vivaldi, so I'll leave aside opening a new issue for what could be my inexperience at work.

One of the nicest features I found in Vivaldi is the side panel view. That seems just the right place to open TabFern: on the side, locked in position and constant during the browsing.

Yet, when I set up the custom panel, the extension won't be loaded, and only a red warning is displayed: Initialization not complete (or not yet complete). Changes will not be saved.
3/13: get window ID
Is this a common problem or I'm missing something?
Thank you. And thank you for providing a nice alternative to TO.

**Comment by cxw42** [comment]
@XellossMetallium I haven't used Vivaldi in a while, but will take a look!

**Comment by cxw42** [comment]
@XellossMetallium Would you please open a new issue?  This is a use case I haven't tested yet, and indeed does not work!

I tried adding a new panel with the extension's URL:

    chrome-extension://hbajjpcdbninabigakflkhiogmmjaakm/win/container.html

It worked in the window I had open, but when I opened a new window, it stopped at "waiting for browser."

In the new issue, please include any details you can about what you are trying (screenshots, URL, ...) so I can test your exact use case.  Thanks!

(And, by the way, thank you for your kind words!)

**Comment by XellossMetallium** [comment]
You're welcome, it's well deserved! I honestly wished to replace that old
extension since forever!
I'll put a reminder for sunday when I'll be at home and I'll open the new
issue. I'll be available for testing, of course.
Cheers!

Il giorno ven 13 set 2019 alle ore 16:13 Chris White <
notifications@github.com> ha scritto:
