### ISSUE TITLE
Flip close/delete (Tabs Outliner style)

### ISSUE THREAD

**Issue by Luckz** [cxw42/TabFern#152]
Tabs Outliner orders the context buttons:
note - delete - close

TabFern orders them:
note (- close and save) - delete

=> I keep pressing the delete button when I mean to press the close button.

**Comment by cxw42** [comment]
@Luckz Thanks for trying TabFern!  I'd like to know your use case.  Are you using both TO and TF at the same time?  Is this something that is preventing you from switching from TO to TF?

**Comment by RiotPharaoh** [comment]
Hi, if you think it will improve UI/UX, then let me know. I'll make a flip :)  @cxw42

**Comment by cxw42** [comment]
@RiotPharaoh Thanks!  I would appreciate this as a feature controlled by a checkbox in Settings | Appearance.  What is your level of JavaScript experience?  (It doesn't need to be very high for this :) )  Have you used node.js and npm?

I am asking because the next release of TabFern uses a Node-based build system.  If you are comfortable with that, I would ask you to please work on a branch off the "switchover" branch.  If not, branch off "master" and I'll merge it by hand when you're ready.

I have created a Gitter chat room at https://gitter.im/TabFern/Lobby .  I am not usually there, but would be happy to meet by arrangement if you need help getting started or have questions or comments.  Thank you for volunteering!  I look forward to working with you.

**Comment by cxw42** [comment]
@RiotPharaoh it just occurred to me - are you looking for a Hacktoberfest credit?  If so, and this issue is more than you have time for in October, I would also accept a PR on the gh-pages branch to update the TabFern web site (e.g., remove the "alpha" indicator, update the documentation to show some of the features that have been added recently).

**Comment by cxw42** [comment]
@Luckz Are you referring to both the window buttons and the tab buttons?  Would you like the order of the tab buttons to change to match the window buttons?

**Comment by cxw42** [comment]
@Luckz @RiotPharaoh I want to let you know I decided to delay #35 and get this one and some other changes out the door first.  I have just merged #163 into the `switchover` branch, which is the current dev mainline.  I expect to release this by the end of the month!

**Comment by Luckz** [comment]
> @Luckz Are you referring to both the window buttons and the tab buttons? Would you like the order of the tab buttons to change to match the window buttons?

(Sorry, very late reply)
It doesn't make sense for window and tab button placement to be different from each other. So for a post- #35 world, yes, both through the same option.

**Comment by cxw42** [comment]
@Luckz thanks - done!
