### ISSUE TITLE
Open window on screen and with reasonable default size/position

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#18]
- [x] When opening a window for the first time, given that the user hasn't saved size and position (since #5 hasn't been implemented yet), open using the default size and a reasonable default position.  See [this SO question](https://stackoverflow.com/q/45693634/2877364).

- [ ] Whenever opening a TabFern window, check the active monitors and make sure the new window is entirely (or at least partly) visible on screen!

**Comment by cxw42** [comment]
Looks like we'll eventually need content scripts per [this](https://stackoverflow.com/q/13141072/2877364).

**Comment by cxw42** [comment]
It's better, but not ideal.  I am thinking that it might be worth just using whatever was the size/position of the last non-popup window the user interacted with.  That doesn't require content scripts, and would at least be predictable.  Does anyone have any comments or suggestions?

**Comment by andr222** [comment]
I use tabfern to define a set of windows, organized by subject.
Some of these windows have as many as 30 tabs.  I would like to close most such windows not currently used, in order to avoid greatly slowing my system.
I like to use all except the tabfern window at exactly the same size & position, overlayed one over the other.  I often hide open windows, using the system menu bar (tableau de bord in french) to select the window to display on top.
Currently new windows open in a very tiny window near the top left corner.   It is difficult and time-consuming to resize and reposition new windows to my preferred size/position.

Suggestion : add  options for preferred size and position of new windows, and option offset for those who would prefer additional windows at a certain offset.  (offset=0 for exactly the same position)
I don't know how easy it is to add such options, but that would be an enormous plus for me.

**Comment by cxw42** [comment]
@andr222 Thanks for the feedback!  Would you please open a separate issue for specifying new-window size and position?  I think that is a reasonable feature and is a different issue than the defaults/on-screen here.

Currently, TF opens new windows at the size of the last-created Chrome window.  Try:

- Opening a new window (not a TF saved window) 
- Navigating to Google or any site
- Sizing the window to the size at which you want restored windows to open
- Closing the window, leaving the TF window open
- Clicking on the TF window and hitting Ctrl-N

If all goes well, the new window will have the same size the window did just before you closed it, and when TF restores a window it will give it the same size.  

That setting is currently per-session, so you may have to do this whenever you start Chrome until the new issue is opened and fixed.

**Comment by andr222** [comment]
Thanks ... your method to reset where TF opens new windows works great : 
Exactly the same size and the position only slightly offset (and easy to ajust).
From what you say, I just have to redo this each session.  Hopefully awaking from hibernating doesn't count as a new session.
You solved a very annoying problem.
Thanks again.

**Comment by cxw42** [comment]
@andr222 glad to hear it, and happy to help!

When you have a few minutes, would you please open the new issue anyway?  It would be a good issue for someone new to TF development to work on, and if you open the issue it is clear that there is user demand :D .  Thanks!

**Comment by cxw42** [comment]
Of the two items listed in the original post, one is done, and the remaining one appears to be the same as #141.   Therefore, I am closing this in favor of #141.
