### ISSUE TITLE
Build script

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#4]
@r4j4h would you please take this one?  

See also discussion in #1.

 - Add a webpack v2 build script that builds into `/dist`.  Assume node/npm/webpack are installed.
 - Document toolchain-installation and building instructions, perhaps in `/HACKING.md` or some such.

For now, please do not minify, and please use non-minified libraries.  I would like to introduce minification later, probably in v1.0 or v1.1.

After some more testing based in [this](https://stackoverflow.com/a/13631525/2877364), I am planning to manually update `/webstore` from `/dist` whenever I update the version on the Chrome Web Store.  That way we won't have to manually `skip-worktree` new files in `/dist`, but the actual running source will still be available to browse online.

**Comment by r4j4h** [comment]
Yup, I am working on this one. :+1:

**Comment by cxw42** [comment]
Current status: using Jasmine for tests.  Hand-copying from the main trees into `/webstore/` for packaging.  No minifying or bundling.  Script `/check-webstore.sh` helps me spot what needs to change, but usually I just do `cp -R src js webstore` and then see what's left to clean up.

**Comment by cxw42** [comment]
One thing that occurred to me today --- whatever we use for building, I would like to be able to support lazy loading of language packs.  I hope someday to have a large enough audience to need translations :) .  I have looked at some Webpack tutorials and seen [`require.ensure()`](https://webpack.js.org/api/module-methods/#require-ensure), so I think this should not be an issue.  (I also see there's a new `import()` but don't know much about it.)

**Comment by cxw42** [comment]
Firefox is much faster than it used to be :) .  It turns out FF largely supports the `chrome.*` APIs for extensions.  Could we set up webpack to build to separate targets, so TabFern could also be available on FF?

**Comment by cxw42** [comment]
@r4j4h I hope all is going well!  Would you have any time next month to work on webpack?  In view of #100, I propose a strawman:

 - `/tabfern`: input
 - `/chrome`: webpack output for Chrome (or `/built/chrome`?)
 - `/ffq`: webpack output for Firefox Quantum (or `/built/ffq`?)
 - `/dist/chrome`: what is currently `/webstore` - manually updated on new releases
 - `/dist/ffq`: the AMO version - manually updated on new releases

There will be inevitably be differences between the browsers, and I'd like to be able to use `#ifdef` or some equivalent facility to automate those.  Plus, FF review requires that Mozilla be able to replicate the build process and get the same result that was submitted for inclusion on AMO.  Standard toolchains are therefore a Good Thing.

Thoughts?  Comments?  I am certainly open to better proposals than the above :) .

**Comment by cxw42** [comment]
@r4j4h I (still ;) ) hope all is going well!  I have just discovered [Brunch](https://brunch.io) and am encouraged - it looks like I may be able to use it to bundle while still keeping my main files at the top level for easier debugging :) .  https://github.com/cxw42/brunch-test

**Comment by cxw42** [comment]
Current build instructions using [Brunch](https://brunch.io/):

 - install [node.js](https://nodejs.org/en/), which includes npm
 - `git clone` TabFern wherever you want it
 - `git checkout switchover`
 - `npm brunch b`
 - Then load `public/` as an unpacked extension.

To make a ZIP for uploading, run `npm run zip`.

**Comment by r4j4h** [comment]
Hi @cxw42, life has been.. lifey. I am glad you found Brunch in the meantime. I do wonder if the weight of webpack will bring much gain over Brunch itself.

Some areas that may still benefit:

- Multiple targets. I am not sure if Brunch supports it out of the box, but we could accomplish it with separate configs and separate build commands hooking it up to each config.  webpack supports [its config returning arrays of configs for multiple targets of different types](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations).
- Runtime loading. While we could manually load files at runtime ourselves, webpack's [lazy loading](https://webpack.js.org/guides/lazy-loading/) might be convenient and provide a framework/pattern for doing it. There may be a plugin for Brunch that shims it in, but all I found after a cursory search was [some official word that Brunch will not support this](https://github.com/brunch/brunch/issues/1341).

For the ability to special case some code for certain browsers, I think we could manage it with either:

- Webpack's [define plugin](https://webpack.js.org/plugins/define-plugin/) could be used to define build-time values to be used as the `#ifdef`  condition. Brunch also supports plugins but I did not see a direct 1-to-1 replacement for Webpack's Define plugin. [jspreprocess-brunch](https://www.npmjs.com/package/jspreprocess-brunch) looks close though.
- Brunch or Webpack could do it via separate brunch configs that each start with a different special entrypoint script that loads the real code in order to define all the per-browser specifics.

I'm still running at reduced capacity but wanted to touch base with you and keep some of these balls rolling..

**Comment by cxw42** [comment]
@r4j4h Thanks for checking back!  I hope things ease up and wish you the best.

Multiple targets/browser special-casing - I do have some Chrome/FF differences, but so far not too many.  Thank you for letting me know about some of the options in case we need more sophistication later.  Brunch does support custom targets, but I haven't played with that much.

Runtime loading - I hadn't thought about this one.  Interesting idea!  I'll think about it next time I look at the module structure.

**Comment by cxw42** [comment]
Closing since Brunch (with one minor tweak) is working for me at this time!  @r4j4h I hope all is going well and COVID isn't getting you down!
