### ISSUE TITLE
Right-click context menus

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#6]
- Add them
- Decide what to put in them

@r4j4h, currently, in fcfa1e4be1aea320ad4509b77e19df8e3afc6eb8, I get the "no shortcut driver" path.  I then observe that shift+right click never unlatches.  I added a `console.log` and it appears that the `win.onkeyup` [here](https://github.com/r4j4h/TabFern/commit/fcfa1e4be1aea320ad4509b77e19df8e3afc6eb8#diff-0a2cbd4297884aa054974860b3ec355cR207) is never being called (perhaps the browser-provided context menu is eating it?).

- Would it make sense to use `addEventListener` instead of the direct `win.on*` assignments?
- Would you please check the non-driver path?  Perhaps I am missing a component you have on your development machine.  Which path do you get?
- Would you please rebase on master when you have a chance?

Feature requests (perhaps a separate, later PR than the above?):
- Would you be willing to add Shift+F10 as a hotkey to pop up the context menu, for the benefit of keyboard users?
- Would you add keyboard nav of the context menu itself?  Currently, the context menu does not take keyboard focus, so it cannot be navigated with arrow keys and Enter.

(Note to self: the options check is not fully implemented per [this](https://github.com/r4j4h/TabFern/blob/right-click-context-menu/src/view/contextMenu/contextMenu.js#L20))

**Comment by r4j4h** [comment]
When you get the "no shortcut driver" does it say anything at the end? I just noticed it appends the `err` instead of passing as a second argument so it may come through Developer Console poorly as [Object object] but hopefully it calls toString on the error. I just pushed some improved error handling to that same branch which may help identify the problem. All the needed files should be there as we are including our libraries in the repo, but I could have missed something.

If the Option is turned off I get `TabFern _tabFernShortcuts.js: Disabled, bailing`
If it's on and everything works I get 
```
TabFern _tabFernShortcuts.js: Installing keyboard listeners
TabFern _tabFernShortcuts.js: Initializing keyboard listener drivers
TabFern _tabFern Drivers dmauro-keypress.js: handleScriptCb loaded with timestamp: 91
TabFern _tabFernShortcuts.js: Driver KeyPress (dmaruo) loaded.
TabFern _tabFernShortcuts.js: Installing keybind configuration
```
and if I rename the file and reload I get
```
TabFern _tabFernShortcuts.js: Installing keyboard listeners
TabFern _tabFernShortcuts.js: Initializing keyboard listener drivers
GET chrome-extension://cgkjbngoblngopaiecmigkemkbmfnlan/js/2dmauro-Keypress-2.1.3-9-80c0f97/keypress-2.1.4.min.js net::ERR_FILE_NOT_FOUND
TabFern _tabFernShortcuts.js: Driver KeyPress (dmaruo) failed to load.
```

Rebased into a new branch and will open a PR as-is with your feature requests as to do items :) 



Regarding your note self, yup, the options check requires refreshing the plugin window to take effect right now but it does look at the setting on load!

**Comment by cxw42** [comment]
Sounds good - closing in favor of #9
