### ISSUE TITLE
Theme selector

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#89]
Supports #86 - if you want a light background, the default-dark theme isn't going to work for you.

**Comment by bluikko** [comment]
Is this intended:
![image](https://user-images.githubusercontent.com/14869000/34784453-debf0b8e-f660-11e7-90cb-a7cd35c0a4e8.png)

Unfortunately I had to redact the favicons and tab names for privacy. Theme was changed to "light" for the first time and at the same time I enabled "connecting lines". If it is a bug should it be a new issue?

I'm not sure why the "Tabfern" is under "Recovered tabs"?

**Comment by cxw42** [comment]
@bluikko Thanks for the report!  To answer your question in the other issue, yes, status is as you see it in these issue records.  December was very full with my day job :) .

No, the black center/white outside is not intentional.  Would you please let me know what your sequence of steps was, if you remember it?  Also, which version?  0.1.13, or are you trying the 0.14.1-rc.1 release candidate?  I tried, but am not able to reproduce in either 0.1.13 or 0.14.1-rc.1.  Is it consistent, or did it only happen once or twice?  (I am hoping the former, since then it might be easier to fix!)

Things showing in "Recovered tabs" is related to #96.

**Comment by cxw42** [comment]
@bluikko I just realized I may be misunderstanding your image.  Is the black box entirely your redaction box?  If the only issue you are mentioning is the Settings window showing in "Recovered tabs," then yes, it is a known issue :) .  Did you use F5 in the TabFern window to apply the theme changes, or did you close and reopen the window?

With the Light theme and connecting lines, is the whole background of the TabFern window white?  If so, that is as it should be.

**Comment by bluikko** [comment]
Yes, the black box is the redaction.

I was questioning about the blue background of the two visible tabs. 

Refresh was not done with F5, the window was re-opened. Does this make a difference?

If it makes difference, maybe the text in the theme settings could say "refresh with F5 or Ctrl-R" instead of just "refresh" to avoid ambiguity.

The two mentioned options were enabled. TF window was closed+re-opened from a window containing only the TF "configuration" tab. Most of my windows, and tabs therein, had dark blue background.  The two options were disabled again, TF window closed, options enabled again, TF window opened. Screenshot taken with now one window+tab only with blue bg.

The TF window showed under "Recovered tabs" under conditions mentioned in #96 so nothing more to add to that.

**Comment by cxw42** [comment]
OK - thanks!  I believe this is unrelated to the theme or connecting lines, so I will consider the discussion of your screenshot as part of #96.
